// export enum QuestionType {
//     MULTIPLE_CHOICE = "MULTIPLE CHOICE",
//     SINGLE_CHOICE = "SINGLE CHOICE",
//     TRUE_FALSE = "TRUE FALSE",
//     FILL_IN_THE_BLANK = "FILL IN THE BLANK",
// }

export enum QuestionType {
    MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
    SINGLE_CHOICE = "SINGLE_CHOICE",
    TRUE_FALSE = "TRUE_FALSE",
    FILL_IN_THE_BLANK = "FILL_IN_THE_BLANK",
}